# Auto-generated by nixos-generate-config. Do not edit manually.
# This file is blacklisted from the module walker and imported explicitly
# in flake.nix so it can be regenerated freely without affecting the module tree.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci_renesas" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules          = [ "amdgpu" ];
  boot.kernelModules                 = [ "kvm-amd" ];
  boot.kernelPackages                = lib.mkIf (lib.versionOlder pkgs.linux.version "5.12") pkgs.linuxPackages_latest;
  boot.extraModulePackages           = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2042eeda-4922-44d8-aa54-6634a2291b04";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device  = "/dev/disk/by-uuid/9F8E-C2AB";
    fsType  = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/d5672815-3af1-4c75-83b1-e543dac193b5"; }
  ];

  nixpkgs.hostPlatform             = lib.mkDefault "x86_64-linux";
  hardware.bluetooth.enable        = true;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
