# Generated by nix-want: signal-desktop
# Roles: desktop workstation (prefix 6)
# Rename the prefix to change roles, delete this file to uninstall.
{ pkgs, ... }:
{
  environment.systemPackages = [ pkgs."signal-desktop" ];
}
