# Generated by nix-want: yazi
# Roles: desktop server workstation (prefix 7)
# Rename the prefix to change roles, delete this file to uninstall.
{ pkgs, ... }:
{
  environment.systemPackages = [ pkgs."yazi" ];
}
