# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = { 
    device = "/dev/disk/by-uuid/f7cb761f-7588-47bc-a969-998b441e5db0";
    fsType = "ext4";
    options = [ "x-gvfs-show" "x-gvfs-name=Storage" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/DE39-0227";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022"  "x-gvfs-show" "x-gvfs-name=Storage" ];
  };
  
  fileSystems."/home/jakub/data" = {
    device = "/dev/disk/by-uuid/d5b482c5-0856-487d-b07c-5394a3deef3d";
    fsType = "ext4";
    options = [ "x-gvfs-show" "x-gvfs-name=Storage" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}